services:
  client:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    working_dir: /usr/src/app/server
    ports:
      - "3001:3001"
    environment:
      - YANDEX_EMAIL=${YANDEX_EMAIL}
      - YANDEX_APP_PASSWORD=${YANDEX_APP_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    restart: unless-stopped
